import { ProductData } from "@/types/type";

// Create 5 products for each of the 4 categories (20 total)
export const dummyProducts: ProductData[] = [
  // Notebooks Category (5 items)
  {
    id: 1,
    name: "Premium Leather Notebook",
    description: "Handcrafted leather notebook with premium paper",
    price: 29.99,
    originalPrice: 39.99,
    category: "Notebooks",
    brand: "Moleskine",
    color: "black",
    imageUrl: "/images/most-viewed/leather-notebook.webp",
    rating: 4.5,
    reviewCount: 128,
    stockCount: 25,
    shippingDays: 1,
    featured: true,
    isNew: true,
    onSale: true,
    dateAdded: "2023-12-01",
  },
  {
    id: 2,
    name: "Dotted Journal",
    description: "Perfect for bullet journaling and planning",
    price: 19.99,
    category: "Notebooks",
    brand: "Leuchtturm1917",
    color: "blue",
    imageUrl: "/images/products/dotted-journal.jpg",
    rating: 4.8,
    reviewCount: 95,
    stockCount: 42,
    shippingDays: 1,
    featured: true,
    isNew: false,
    onSale: false,
    dateAdded: "2023-10-15",
  },
  {
    id: 3,
    name: "Pocket Notebook Set",
    description: "Set of 3 pocket-sized notebooks",
    price: 12.99,
    category: "Notebooks",
    brand: "Moleskine",
    color: "black",
    imageUrl: "/placeholder.svg?height=300&width=300&text=Pocket Notebooks",
    rating: 4.2,
    reviewCount: 67,
    stockCount: 18,
    shippingDays: 2,
    featured: false,
    isNew: false,
    onSale: false,
    dateAdded: "2023-09-20",
  },
  {
    id: 4,
    name: "Waterproof Notebook",
    description: "All-weather writing paper",
    price: 24.99,
    category: "Notebooks",
    brand: "Leuchtturm1917",
    color: "yellow",
    imageUrl: "/images/products/waterproof-notebook.jpg",
    rating: 4.0,
    reviewCount: 42,
    stockCount: 7,
    shippingDays: 3,
    featured: false,
    isNew: true,
    onSale: false,
    dateAdded: "2024-01-05",
  },
  {
    id: 5,
    name: "Luxury Hardcover Journal",
    description: "Premium hardcover with gold embossing",
    price: 34.99,
    originalPrice: 44.99,
    category: "Notebooks",
    brand: "Moleskine",
    color: "red",
    imageUrl: "/images/products/luxury-hard-notebook.jpg",
    rating: 4.9,
    reviewCount: 156,
    stockCount: 12,
    shippingDays: 2,
    featured: true,
    isNew: false,
    onSale: true,
    dateAdded: "2023-11-10",
  },

  // Pens & Pencils Category (5 items)
  {
    id: 6,
    name: "Fountain Pen Set",
    description: "Elegant fountain pen with 3 ink cartridges",
    price: 5.2,
    category: "Pens & Pencils",
    brand: "Lamy",
    color: "black",
    imageUrl: "/images/products/fountain-pen.webp",
    rating: 4.7,
    reviewCount: 89,
    stockCount: 15,
    shippingDays: 2,
    featured: true,
    isNew: false,
    onSale: false,
    dateAdded: "2023-08-15",
  },
  {
    id: 7,
    name: "Precision Mechanical Pencil",
    description: "0.5mm lead with cushioned tip",
    price: 14.99,
    category: "Pens & Pencils",
    brand: "Pilot",
    color: "silver",
    imageUrl: "/images/products/precise-pencil.webp",
    rating: 4.5,
    reviewCount: 112,
    stockCount: 30,
    shippingDays: 1,
    featured: false,
    isNew: true,
    onSale: false,
    dateAdded: "2024-02-01",
  },
  {
    id: 8,
    name: "Fountain Pen",
    description: "Set of 12 colorful gel pens",
    price: 7.1,
    originalPrice: 19.99,
    category: "Pens & Pencils",
    brand: "Pilot",
    color: "blue",
    imageUrl: "/images/pen-n-pencils.jpg",
    rating: 4.3,
    reviewCount: 78,
    stockCount: 22,
    shippingDays: 1,
    featured: false,
    isNew: false,
    onSale: true,
    dateAdded: "2023-10-05",
  },
  {
    id: 9,
    name: "Calligraphy Pen Set",
    description: "Professional calligraphy set with nibs",
    price: 49.99,
    category: "Pens & Pencils",
    brand: "Lamy",
    color: "gold",
    imageUrl: "/images/products/call-pen.jpg",
    rating: 4.6,
    reviewCount: 64,
    stockCount: 8,
    shippingDays: 3,
    featured: true,
    isNew: false,
    onSale: false,
    dateAdded: "2023-09-12",
  },
  {
    id: 10,
    name: "Sticky Notes",
    description: "Set of sticky ntoes in different colors",
    price: 12.99,
    category: "notes",
    brand: "Pilot",
    color: "black",
    imageUrl: "/images/sticky-notes.jpg",
    rating: 4.1,
    reviewCount: 53,
    stockCount: 35,
    shippingDays: 1,
    featured: false,
    isNew: false,
    onSale: false,
    dateAdded: "2023-11-20",
  },

  // Planners Category (5 items)
  {
    id: 11,
    name: "Annual Planner 2024",
    description: "Comprehensive yearly planner with monthly tabs",
    price: 29.99,
    category: "Planners",
    brand: "Leuchtturm1917",
    color: "green",
    imageUrl: "/images/products/annual-plan.jpg",
    rating: 4.8,
    reviewCount: 142,
    stockCount: 50,
    shippingDays: 1,
    featured: true,
    isNew: true,
    onSale: false,
    dateAdded: "2023-12-15",
  },
  {
    id: 12,
    name: "Goemtry Box",
    description: "All the material found here",
    price: 14.99,
    category: "Planners",
    brand: "Moleskine",
    color: "black",
    imageUrl: "/images/products/goemtery.jpg",
    rating: 4.2,
    reviewCount: 87,
    stockCount: 25,
    shippingDays: 2,
    featured: false,
    isNew: false,
    onSale: false,
    dateAdded: "2023-10-10",
  },
  {
    id: 13,
    name: "Academic Planner",
    description: "August-July academic year planner",
    price: 24.99,
    originalPrice: 29.99,
    category: "Planners",
    brand: "Leuchtturm1917",
    color: "blue",
    imageUrl: "/images/products/academic.jpeg",
    rating: 4.5,
    reviewCount: 76,
    stockCount: 18,
    shippingDays: 2,
    featured: false,
    isNew: false,
    onSale: true,
    dateAdded: "2023-07-20",
  },

  {
    id: 15,
    name: "5-Year Journal",
    description: "Document 5 years of memories in one book",
    price: 39.99,
    category: "Planners",
    brand: "Leuchtturm1917",
    color: "brown",
    imageUrl: "/images/products/5-year-journey.jpeg",
    rating: 4.9,
    reviewCount: 67,
    stockCount: 5,
    shippingDays: 3,
    featured: false,
    isNew: false,
    onSale: false,
    dateAdded: "2023-11-05",
  },

  // Desk Accessories Category (5 items)
  {
    id: 16,
    name: "Wooden Pen Holder",
    description: "Elegant wooden desk organizer",
    price: 24.99,
    category: "Desk Accessories",
    brand: "Lamy",
    color: "brown",
    imageUrl: "/images/products/wooden-holder.jpeg",
    rating: 4.4,
    reviewCount: 58,
    stockCount: 20,
    shippingDays: 2,
    featured: false,
    isNew: false,
    onSale: false,
    dateAdded: "2023-09-25",
  },
  {
    id: 17,
    name: "Leather Desk Pad",
    description: "Premium leather desk protector and mouse pad",
    price: 49.99,
    originalPrice: 59.99,
    category: "Desk Accessories",
    brand: "Moleskine",
    color: "black",
    imageUrl: "/images/products/leather-desk-pad.jpeg",
    rating: 4.6,
    reviewCount: 92,
    stockCount: 15,
    shippingDays: 2,
    featured: true,
    isNew: false,
    onSale: true,
    dateAdded: "2023-10-20",
  },

  {
    id: 19,
    name: "Adjustable Bookstand",
    description: "Wooden bookstand with adjustable angles",
    price: 34.99,
    category: "Desk Accessories",
    brand: "Leuchtturm1917",
    color: "brown",
    imageUrl: "/images/products/adjustable-clock.jpeg",
    rating: 4.5,
    reviewCount: 73,
    stockCount: 10,
    shippingDays: 3,
    featured: false,
    isNew: false,
    onSale: false,
    dateAdded: "2023-08-10",
  },
  {
    id: 20,
    name: "Luxury Desk Clock",
    description: "Analog desk clock with silent movement",
    price: 79.99,
    originalPrice: 99.99,
    category: "Desk Accessories",
    brand: "Lamy",
    color: "silver",
    imageUrl: "/images/products/luxury-clock.jpeg",
    rating: 4.8,
    reviewCount: 38,
    stockCount: 5,
    shippingDays: 2,
    featured: true,
    isNew: false,
    onSale: true,
    dateAdded: "2023-11-15",
  },
]

